# Generated by Django 5.0.1 on 2024-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 13), ('age__lt', 35)), name='Age is valid between 13 and 35'),
        ),
    ]
